name: CI

on:
  pull_request:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install pytest hypothesis mypy black isort flake8
      - name: Lint (flake8)
        run: flake8 . || true
      - name: Type Check (mypy)
        run: |
          echo "[mypy]\nignore_missing_imports = True" > mypy.ini
          mypy . || true
      - name: Tests
        run: pytest -q || true
      - name: Summary
        run: echo "CI skeleton executed"
